Vagrant.configure(2) do |config|
  config.vm.box = "debian/stretch64"
  config.vm.define "master" do |master|
    master.vm.network "private_network", ip: "192.168.56.10"

    master.vm.hostname = "master"

    config.vm.provision "chef_solo" do |chef|
      chef.add_recipe "dokuwiki"
      chef.add_recipe "rsync"
    end
  end

  config.vm.define "slave-1" do |slave|
    slave.vm.box = "debian/stretch64"
    slave.vm.network "private_network", ip: "192.168.56.11"
    slave.vm.hostname = "slave-1"

    config.vm.provision "chef_solo" do |chef|
      chef.add_recipe "dokuwiki"
      chef.add_recipe "rsync"
    end
  end
end